### ISSUE TITLE
Rounded flags

### ISSUE THREAD

**Issue by hacknug** [LeCoupa/vueflags#14]
Noticed you only had the rectangular version of the flags set on the repo and I needed the rounded ones for my project. I have them all properly named and cleaned up on one of my projects in case anyone needs them. Ideally they'd sit under `/assets/flags-rounded` and the same could be done for the square ones.

Let me know if you're interested on a PR that adds them. The only issue I can think of is flags will need to be contributed to all sets instead of just one like you're doing now. If that's too much overhead, I'll probably share them on a new repo and link back to the plugin.

**Comment by hacknug** [comment]
Sure! They're the ones under the Rounded tab of [the author's site](https://www.flaticon.com/packs/countrys-flags).

**Comment by LeCoupa** [comment]
Hello @hacknug, I will redesign to make them the same as the ones I use. I am closing the issue for now. 🙂
