### ISSUE TITLE
Vue 3 support

### ISSUE THREAD

**Issue by Quasarman** [LeCoupa/vueflags#26]
Hello,

will you plan to add support for Vue3?

Best Regards

**Comment by picks44** [comment]
+1

**Comment by LeCoupa** [comment]
I am not familiar with Vue 3, to be honest. If you can help me on this one and give me a few great resources I should read to learn it. It would be great. :)

**Comment by Tahul** [comment]
Hey 👋 

I'll try writing a PR for this soon 😃 

Shouldn't be hard!

**Comment by Quasarman** [comment]
Hello,

Thanks a lot for adding this!
Would it be possible that you create a release tag for such a big change? Since the asset loaction has changed it breaks some stuff when automatically upgrading/ fetching the assets from the previous location.

BR

**Comment by conradfr** [comment]
Hello, how would you use the library in a component, given that Vue.use has been removed ?

Maybe it's obvious but I'm new to Vue3 and trying to convert a Vue2 project :)

**Comment by conradfr** [comment]
@Tahul besides my question above (I don't think the README is sufficiently updated for Vue3), is your merged version supposed to work without TypeScript ?
