### ISSUE TITLE
Missing flags - compliance with ISO 3166-1

### ISSUE THREAD

**Issue by Quasarman** [LeCoupa/vueflags#6]
Hello first let me say I love the component and the effort you put into this project. 
I noticed that some flags are missing when cross-checking them with the countries specified by the ISO 3166-1 - source: https://en.wikipedia.org/wiki/ISO_3166-1#Current_codes 
Maybe you find the time to implement the missing flags or can show me the process how to add them myself so they comply with the format used within vueflags.
Below I provided a list of missing flags:
|country name|filename|
|------------|--------|
|Antarctica|aq.svg|
|Bouvet Island|bv.svg|
|United States Minor Outlying Islands|um.svg|
|French Guiana|gf.svg|
|French Southern Territories|tf.svg|
|Guadeloupe|gp.svg|
|Guyana|gy.svg|
|Heard Island and McDonald Islands|hm.svg|
|Kiribati|ki.svg|
|Mayotte|yt.svg|
|New Caledonia|nc.svg|
|Réunion|re.svg|
|Saint Helena, Ascension and Tristan da Cunha|sh.svg|
|Saint Martin (French part)|mf.svg|
|Saint Pierre and Miquelon|pm.svg|
|South Georgia and the South Sandwich Islands|gs.svg|
|Svalbard and Jan Mayen|sj.svg|
|Swaziland|sz.svg|
|Tuvalu|tv.svg|
|Wallis and Futuna|wf.svg|

Thanks in advance!

**Comment by Quasarman** [comment]
I was cross-checking the data with this site: https://restcountries.eu/. It provides all kind of information about countries and the list is ISO conform. They also provide links to the respective country svgs but they seem to have much more details than the ones within vueflags which is not what im looking for. Maybe they can be used as a reference point. This is for example the flag for Antarctiqua which is missing within vueflags: https://restcountries.eu/data/ata.svg

**Comment by LeCoupa** [comment]
Thank you @Quasarman , I will update this during the weekend.  :)

**Comment by LeCoupa** [comment]
You can add the svg flags here if you have some time: https://github.com/growthbunker/vueflags/tree/master/assets/flags

And add them flags here:
https://github.com/growthbunker/vueflags/blob/master/src/data/flags.js

**Comment by Quasarman** [comment]
Wow, thanks for the quick response! Im looking forward to it. Any flags you don't find the time to implement I will gladly take care of. Next few weeks im quite busy but if you don't manage to add all of the missing ones I'll do so :)

**Comment by LeCoupa** [comment]
Thanks, I will try to do this on Saturday. :) I will keep you up-to-date!

**Comment by Quasarman** [comment]
Hey I just wanted to check if there are any updates on the lags which are missing 😊

**Comment by LeCoupa** [comment]
Sorry I did not have the time to work on it. Maybe this weekend :)

**Comment by Quasarman** [comment]
Ah ok no worries, it isn't really urgent, take your time with it :)

**Comment by LeCoupa** [comment]
Should be good now. :) Update your package to `0.1.0` and replace the flag directory by this one.

https://github.com/LeCoupa/vueflags/tree/master/assets/flags

**Comment by Quasarman** [comment]
Awesome thanks again for the great work!
