### ISSUE TITLE
Prop name wrong?

### ISSUE THREAD

**Issue by j0hannes** [LeCoupa/vueflags#9]
> [Vue tip]: Prop "iconpath" is passed to component <Anonymous>, but the declared prop name is "iconPath". Note that HTML attributes are case-insensitive and camelCased props need to use their kebab-case equivalents when using in-DOM templates. You should probably use "icon-path" instead of "iconPath".

**Comment by LeCoupa** [comment]
Can you copy your code here? You should use it like this, not in your component prop.

```
import VueFlags from "@growthbunker/vueflags";

Vue.use(VueFlags, {
  // Specify the path of the folder where the flags are stored.
  iconPath: '/images/vueflags/flags/',
});
```

The documentation is available here: https://www.growthbunker.dev/vueflags/

**Comment by j0hannes** [comment]
I'm including it via <script> in the header section, how can I change the parameter there?
